//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Resource.rc
//
#define IDC_LISTCTRL_TABLE              1000
#define IDC_EDIT_DIALOG_USER_SETTINGS_NAME 1001
#define IDC_EDIT_DIALOG_USER_SETTINGS_LOGIN 1002
#define IDC_EDIT_DIALOG_USER_SETTINGS_PASSWORD 1003
#define IDC_EDIT_DIALOG_USER_SETTINGS_JOB_TITLE 1004
#define IDC_EDIT_DIALOG_USER_SETTINGS_DESCRIPTION 1005
#define IDC_EDIT_DIALOG_USER_SETTINGS_TELEPHONE 1006
#define IDC_BUTTON_DIALOG_USER_SETTINGS_CANCEL 1007
#define IDC_BUTTON_DIALOG_USER_SETTINGS_OK 1008
#define IDC_EDIT_DIALOG_SERVER_SETTINGS_PORT 1008
#define IDC_BUTTON_DIALOG_SERVER_SETTINGS_CANCEL 1009
#define IDC_BUTTON_DIALOG_SERVER_SETTINGS_OK 1010
#define IDC_CHECK_DIALOG_SERVER_SETTINGS_RUN_ON_WINDOWS 1011
#define IDR_MENU_LIST                   2000
#define IDD_DIALOG_USER_SETTINGS        2001
#define IDR_MENU_MAIN                   2003
#define IDD_DIALOG_SERVER_SETTINGS      2004
#define IDI_ICON_MAIN                   2005
#define IDC_MENU_LIST_ADD_USER          4001
#define IDC_MENU_LIST_EDIT_USER         4002
#define IDC_MENU_LIST_DELETE_USER       4003
#define IDC_MENU_LIST_SET_LEADER        4004
#define IDC_MENU_LIST_RESET_LEADER      4005
#define IDC_MENU_MAIN_SETTINGS          4006
#define IDC_MENU_SYSTRAY_EXIT			4007

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        2006
#define _APS_NEXT_COMMAND_VALUE         4008
#define _APS_NEXT_CONTROL_VALUE         1012
#define _APS_NEXT_SYMED_VALUE           3000
#endif
#endif
